language: node_js

node_js:
  - "0.11"
  - "0.10"
  - "0.8"

notifications:
  email: false

before_install: sudo apt-get install xvfb libsecret-1-dev 
script: xvfb-run ./script/cibuild

git:
  depth: 10
